[package]
name = "html_hybrid_parser"
version = "0.1.0"
edition = "2024"

[dependencies]
astral-tl = { git = "https://github.com/quaero-search/astral-tl" }
kuchikiki = { git = "https://github.com/quaero-search/kuchikiki" }
phf = { version = "0.13.1", features = ["macros"] }
html-escape = "0.2.13"
